name: Plugin-Template
version: 1.0.0
author: Aleksi Lassila
main: me.aleksilassila.template.Main
api-version: 1.15
commands:
  example:
    description: Template command
    usage: /<command>
    aliases: [t]

permissions:
  template.example:
    description: Description
    default: "op"
